function update_comments(a){var c=$("#n_comentarios-"+a).html();c++;!1==c&&(c=1);$("#n_comentarios-"+a).html(c);1==c&&$("#t_comentarios-"+a).html(" comentario")}function setOpacity(a){obj=document.getElementById("ajaxcomments");container=document.getElementById("ajaxcontainer");obj.style.filter="alpha(opacity:"+a+")";obj.style.KHTMLOpacity=a/100;obj.style.MozOpacity=a/100;obj.style.opacity=a/100;container.style.height=a*obj.offsetHeight/100+10+"px"}
function fadeIn(a){100>=a&&(setOpacity(a),window.setTimeout("fadeIn("+(a+50)+")",25))}function startFade(){setOpacity(document.getElementById("ajaxcomments"),0);document.getElementById("ajaxcomments").style.visibility="visible";fadeIn(0)}
function submit_comment(){if(""==document.getElementById("comment").value)return document.getElementById("error_com").innerHTML="Comentario vac\u00edo",document.getElementById("spinner").className="ko",document.getElementById("comment").focus(),!1;var a=document.getElementById("comment").value,c=document.getElementById("process").value,e=document.getElementById("randkey").value,d=document.getElementById("link_id").value,f=document.getElementById("user_id").value,g=document.getElementById("comentario-admin").checked,
h=document.getElementById("comentario-especial").checked,b=new XMLHttpRequest;b&&(document.getElementById("submit_com").disabled=!0,document.getElementById("comment").disabled=!0,document.getElementById("comentario-admin").disabled=!0,document.getElementById("comentario-especial").disabled=!0,document.getElementById("spinner").className="loading",b.onreadystatechange=function(){if(4==b.readyState){var a=b.responseText;if("OK:"==String(a).substring(0,3))return document.getElementById("spinner").className=
"ok",document.getElementById("comment").value="",document.getElementById("ajaxcomments").innerHTML=String(a).substring(3),update_comments(d),startFade(),!0;document.getElementById("spinner").className="ko";document.getElementById("submit_com").disabled=!1;document.getElementById("comment").disabled=!1;document.getElementById("comentario-admin").disabled=!1;document.getElementById("comentario-especial").disabled=!1;document.getElementById("error_com").innerHTML=String(a).substring(3);return!1}},b.open("POST",
"/ajax/new_comment.php",!0),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.send("comment_content="+encodeURIComponent(a)+"&process="+c+"&randkey="+e+"&link_id="+d+"&user_id="+f+"&type="+g+"&especial="+h))}
function edit_comment(a){if(""==document.getElementById("comment_"+a).value)return document.getElementById("error_com_"+a).innerHTML="Comentario vac\u00edo",document.getElementById("spinner_"+a).className="spinner ko",document.getElementById("comment_"+a).focus(),!1;var c=document.getElementById("comment_"+a).value,e=document.getElementById("key_"+a).value,d=document.getElementById("link_id_"+a).value,f=document.getElementById("user_id_"+a).value,g=document.getElementById("comentario-admin_"+a).checked,
h=document.getElementById("comentario-especial_"+a).checked,b=new XMLHttpRequest;b&&(document.getElementById("submit_com_"+a).disabled=!0,document.getElementById("comment_"+a).disabled=!0,document.getElementById("comentario-admin_"+a).disabled=!0,document.getElementById("comentario-especial_"+a).disabled=!0,document.getElementById("spinner_"+a).className="spinner loading",b.onreadystatechange=function(){if(4==b.readyState){var c=b.responseText;if("OK:"==String(c).substring(0,3))return document.getElementById("spinner_"+
a).className="spinner ok",document.getElementById("comment_"+a).value="",document.getElementById("ccontainer-"+a).innerHTML=String(c).substring(3),!0;document.getElementById("spinner_"+a).className="spinner ko";document.getElementById("submit_com_"+a).disabled=!1;document.getElementById("comment_"+a).disabled=!1;document.getElementById("comentario-admin_"+a).disabled=!1;document.getElementById("comentario-especial_"+a).disabled=!1;document.getElementById("error_com_"+a).innerHTML=String(c).substring(3);
return!1}},b.open("POST","/ajax/edit_comment.php?id="+a,!0),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.send("id="+a+"&comment_content="+encodeURIComponent(c)+"&process=editcomment&key="+e+"&link_id="+d+"&user_id="+f+"&type="+g+"&especial="+h))};
