function jonea(a,b,c,d){var e=base_url+"backend/jonea.php",e=e+"?"+("id="+b+"&user="+a+"&md5="+d);disable_vote_link(b,"espera...","#adcee9");$.getJSON(e,function(a){parseLinkAnswer(c,a)})}function joneo_aleatorio(a,b,c,d){var e=base_url+"backend/aleatorio.php",e=e+"?"+("id="+b+"&user="+a+"&md5="+d);disable_vote_link(b,"lloneandoo!","#adcee9");$.getJSON(e,function(a){parseLinkAnswer(c,a);parsealeatorioLinkAnswer(c,a)})}
function karga_mezuak(a,b){var c=base_url+"backend/mezuak.php";$.getJSON(c+"?"+("id="+a+"&md5="+b),function(b){ErantzunaProzesatu(a,b)});setTimeout('karga_mezuak("'+a+'", "'+b+'")',4E4)}function idatzi_mezuak(a){$("#mezuak").html("<span>"+a+"</span>")}function ErantzunaProzesatu(a,b){if(b.error||a!=b.id)return idatzi_mezuak(".. error al actualizar los datos .."),alert("Error: "+b.error),!1;idatzi_mezuak(b.mezuberri);return!1}
function irakurri_mezua(a,b,c,d,e){var f=base_url+"backend/mezuak_ikusi.php";$.ajax({url:f+"?"+("id="+b+"&md5="+c+"&mid="+a+"&mota="+d+"&eg="+e),dataType:"html",success:function(b){idatzi_mezuguztia(b,a)}})}function ezabatu_mezua(a,b,c,d){var e=base_url+"backend/ezabatu_mezua.php",e=e+"?"+("id="+b+"&md5="+c+"&mid="+a+"&mota="+d);document.getElementById("mezuak"+a).style.display="none";$.ajax({url:e,dataType:"html",success:function(b){$("#mezuak"+a).html("no data")}})}
function clk(a,b){a.href=base_url+"backend/go.php?id="+b;return!0}function idatzi_mezuguztia(a,b){$("#mezuak"+b).html(a)}function ProzesatuMezua(a,b,c){if(b.error||a!=b.id)return idatzi_mezuguztia(".. error al actualizar los datos ..",c),alert("Error: "+b.error),!1;idatzi_mezuguztia(b.mezuberri,c);return!1}
function votar_comentario(a,b,c){var d=base_url+"backend/comentario_voto.php";$.getJSON(d+"?"+("id="+b+"&user="+a+"&value="+c),function(a){if(a.error)return alert("Error: "+a.error),!1;$("#vc-"+b).html(a.votes+"");$("#vk-"+b).html(a.karma+"");0<a.image.length&&$("#c-votes-"+b).html("<img style=\"background: url('/img/iconos/sprite.png') "+a.image+' no-repeat;" src="/img/estructura/pixel.gif" width="12" height="8"/>')})}
function poll_comment_vote(a,b,c){var d=base_url+"backend/poll_comment_vote.php";$.getJSON(d+"?"+("id="+b+"&user="+a+"&value="+c),function(a){if(a.error)return alert("Error: "+a.error),!1;$("#vc-"+b).html(a.votes+"");$("#vk-"+b).html(a.karma+"");0<a.image.length&&$("#c-votes-"+b).html("<img style=\"background: url('/img/iconos/sprite.png') "+a.image+' no-repeat;" src="/img/estructura/pixel.gif" width="12" height="8"/>')})}
function votar_corto(a,b,c){var d=base_url+"backend/corto_voto.php";$.getJSON(d+"?"+("id="+b+"&user="+a+"&value="+c),function(a){if(a.error)return alert("Error: "+a.error),!1;$("#vc-"+b).html(a.votes+"");$("#vk-"+b).html(a.karma+"");0<a.image.length&&$("#c-votes-"+b).html("<img style=\"background: url('/img/iconos/sprite.png') "+a.image+' no-repeat;" src="/img/estructura/pixel.gif" width="12" height="8"/>')})}
function votar_notita(a,b,c){var d=base_url+"backend/notita_voto.php";$.getJSON(d+"?"+("id="+b+"&user="+a+"&value="+c),function(a){if(a.error)return alert("Error: "+a.error),!1;$("#vc-"+b).html(a.votes+"");$("#vk-"+b).html(a.karma+"");0<a.image.length&&$("#c-votes-"+b).html("<img style=\"background: url('/img/iconos/sprite.png') "+a.image+' no-repeat;" src="/img/estructura/pixel.gif" width="12" height="8"/>')})}
function disable_vote_link(a,b,c){$("#a-va-"+a).html("<span>"+b+"</span>");$("#a-va-"+a).css("background",c)}
function parseLinkAnswer(a,b){$("#problem-"+a).hide();if(b.error||a!=b.id)return disable_vote_link(a,"vaya :-(","#adcee9"),alert("Error: "+b.error),!1;votes=parseInt(b.votes)+parseInt(b.anonymous);$("#a-votes-"+b.id).html()!=votes&&($("#a-votes-"+b.id).hide(),$("#a-votes-"+b.id).html(votes+""),$("#a-votes-"+b.id).fadeIn("slow"));$("#a-neg-"+b.id).html(b.negatives+"");$("#a-usu-"+b.id).html(b.votes+"");$("#a-ano-"+b.id).html(b.anonymous+"");$("#a-karma-"+b.id).html(b.karma+"");0<b.value?"no"==b.aleatorio_valor?
disable_vote_link(b.id,"&#161;biibaaa!","#FFFFFF"):disable_vote_link(b.id,"vali\u00f3 "+b.aleatorio_valor,"#FFFFFF"):0>b.value&&disable_vote_link(b.id,":-(","#FFFFFF");return!1}
function parsealeatorioLinkAnswer(a,b){if(b.error||a!=b.id)return disable_vote_link(a,"vaya :-(","#adcee9"),alert("Error: "+b.error),!1;color=0==b.aleatorios_positivos?"#aaa":"";$("#a-ale_pos-"+b.id).html(b.aleatorios_positivos+"");document.getElementById("a-ale_pos-"+b.id).style.color=color;$("#a-ale_neg-"+b.id).html(b.aleatorios_negativos+"");color=0==b.aleatorios_negativos?"":"red";document.getElementById("a-ale_neg-"+b.id).style.color=color;return!1}
function securePasswordCheck(a){5<a.value.length&&a.value.match("^(?=.{6,})(?=(.*[a-z].*))(?=(.*[A-Z0-9].*)).*$","g")?a.value.match("^(?=.{8,})(?=(.*[a-z].*))(?=(.*[A-Z].*))(?=(.*[0-9].*)).*$","g")?a.className="verde":a.className="amarillo":a.className="rojo";return!1}function checkEqualFields(a,b){a.className=a.value==b.value?"verde":"rojo";return!1}function enablebutton(a,b,c){c=c.value;null!=b&&(b.disabled=!1);a.disabled=0<c.length?!1:!0}
function checkfield(a,b,c){var d=base_url+"backend/checkfield.php?type="+a+"&name="+encodeURIComponent(c.value);$.get(d,function(d){"OK"==d?($("#"+a+"checkitvalue").html('<br/><span style="color:black">"'+encodeURI(c.value)+'": '+d+"</span>"),b.submit.disabled=""):($("#"+a+"checkitvalue").html('<br/><span style="color:red">"'+encodeURI(c.value)+'": '+d+"</span>"),b.submit.disabled="disabled")});return!1}
function check_checkfield(a,b){if((field=document.getElementById(a))&&!field.checked)return alert(b),!1}function report_problem(a,b,c,d){if(0!=a.ratings.value){if(!confirm("\u00bfEst\u00e1s seguro de querer votar '"+a.ratings.options[a.ratings.selectedIndex].text+"'?"))return a.ratings.selectedIndex=0,!1;$.getJSON(base_url+"backend/negativo.php?"+("id="+c+"&user="+b+"&md5="+d+"&value="+a.ratings.value),function(a){parseLinkAnswer(c,a)});return!1}}
function obtener(a,b,c,d,e){a=base_url+"backend/"+a+"?id="+e+"&p="+d+"&type="+b;$("#"+c).load(a)}
function modal_from_ajax(a,b){"undefined"==typeof b&&(b="&nbsp");$.modal('<div class="header" id="modalHeader" style="z-index: 10;display: block;" ><div id="modalTitle">'+b+'</div><a href="#" title="Cerrar" class="modalCloseX modalClose"><img src="/img/estructura/pixel.gif" width="16" height="16"/></a></div><div style="z-index: 10;display: block;" class="content" id="modalContent">Loading...</div>',{overlay:"50"});$.get(a,function(a){$("#modalContent").html(a)})}
function textCounter(a,b,c){a.value.length>c?a.value=a.value.substring(0,c):b.value=c-a.value.length}function tooltip(){}tooltip.id="tooltip";tooltip.main=null;tooltip.offsetx=10;tooltip.offsety=10;tooltip.shoffsetx=8;tooltip.shoffsety=8;tooltip.x=0;tooltip.y=0;tooltip.tooltipShadow=null;tooltip.tooltipText=null;tooltip.title_saved="";tooltip.saveonmouseover=null;tooltip.timeout=null;tooltip.active=!1;tooltip.cache=new JSOC;tooltip.ie=document.all?!0:!1;
tooltip.ie5=tooltip.ie?0<navigator.userAgent.indexOf("MSIE 5"):!1;tooltip.dom2=document.getElementById&&!tooltip.ie5?!0:!1;
tooltip.show=function(a,b){if(!1==this.dom2)return!1;null==this.tooltipShadow&&(this.tooltipShadow=document.createElement("div"),this.tooltipShadow.setAttribute("id","tooltip-shadow"),document.body.appendChild(tooltip.tooltipShadow),this.tooltipText=document.createElement("div"),this.tooltipText.setAttribute("id","tooltip-text"),document.body.appendChild(this.tooltipText));this.saveonmouseover=document.onmousemove;document.onmousemove=this.mouseMove;this.mouseMove(a);this.setText(b);this.tooltipText.style.visibility=
"visible";this.tooltipShadow.style.visibility="visible";this.active=!0;return!1};tooltip.setText=function(a){tooltip.tooltipShadow.style.width="0px";tooltip.tooltipShadow.style.height="0px";this.tooltipText.innerHTML=a;setTimeout("tooltip.setShadow()",1);return!1};tooltip.setShadow=function(){tooltip.tooltipShadow.style.width=tooltip.tooltipText.clientWidth+"px";tooltip.tooltipShadow.style.height=tooltip.tooltipText.clientHeight+"px"};
tooltip.hide=function(a){if(!1==this.dom2)return!1;document.onmousemove=this.saveonmouseover;this.saveonmouseover=null;null!=this.tooltipShadow&&(this.tooltipText.style.visibility="hidden",this.tooltipShadow.style.visibility="hidden",this.tooltipText.innerHTML="");this.active=!1};tooltip.mouseMove=function(a){tooltip.ie?(tooltip.x=event.clientX,tooltip.y=event.clientY):(tooltip.x=a.pageX,tooltip.y=a.pageY);tooltip.moveTo(tooltip.x+tooltip.offsetx,tooltip.y+tooltip.offsety)};
tooltip.moveTo=function(a,b){this.ie&&(a+=document.documentElement.scrollLeft,b+=document.documentElement.scrollTop);0<this.tooltipText.clientWidth&&(0<document.documentElement.clientWidth&&a>0.55*document.documentElement.clientWidth)&&(a=a-this.tooltipText.clientWidth-2*this.offsetx);this.tooltipText.style.left=a+"px";this.tooltipText.style.top=b+"px";xLS=a+this.shoffsetx;yLS=b+this.shoffsety;this.tooltipShadow.style.left=xLS+"px";this.tooltipShadow.style.top=yLS+"px"};
tooltip.c_show=function(a,b,c,d){if(!1==this.dom2)return!1;if(0==c&&0<d)this.ajax_delayed(a,"get_link.php",d);else if("id"==b)this.ajax_delayed(a,"get_comment_tooltip.php",c+"&link="+d);else if("order"==b)this.ajax_delayed(a,"get_comment_tooltip.php",c+"&link="+d);else return text=c,this.show(a,text)};
tooltip.poll_c_show=function(a,b,c,d){if(!1==this.dom2)return!1;if(0==c&&0<d)this.ajax_delayed(a,"get_encuesta.php",d);else if("id"==b)this.ajax_delayed(a,"get_opinion_tooltip.php",c+"&link="+d);else if("order"==b)this.ajax_delayed(a,"get_opinion_tooltip.php",c+"&link="+d);else return text=c,this.show(a,text)};tooltip.clear=function(a){null!=this.timeout&&(clearTimeout(this.timeout),this.timeout=null);this.hide(a)};
tooltip.ajax_delayed=function(a,b,c,d){d=d||6E5;if(this.active)return!1;void 0!=(object=this.cache.get(b+c))?tooltip.show(a,object[b+c]):(this.show(a,"cargando..."),this.timeout=setTimeout("tooltip.ajax_request('"+b+"', '"+c+"', "+d+")",100))};tooltip.ajax_request=function(a,b,c){var d=base_url+"backend/"+a+"?id="+b;tooltip.timeout=null;$.ajax({url:d,dataType:"html",success:function(d){tooltip.cache.set(a+b,d,{ttl:c});tooltip.setText(d)}})};
function applyTag(a,b){(obj=document.getElementById(a))&&wrapText(obj,b,b)}
function wrapText(a,b){if("number"==typeof a.selectionStart){var c=a.selectionStart,d=a.selectionEnd;if(c==d||d<c)return!1;a.value=a.value.substring(0,c)+replaceText(a.value.substring(c,d),b)+a.value.substring(d,a.value.length)}else if(document.selection){a.focus();c=document.selection.createRange();if(c.parentElement()!=a||""==c.text)return!1;"string"==typeof c.text&&(document.selection.createRange().text=replaceText(c.text,b))}else a.value+=text}
function replaceText(a,b){a=a.replace(/(^|\s)[\*_]([^\s]+)[\*_]/gm,"$1$2");return a=a.replace(/([^\s]+)/gm,b+"$1"+b)}function reportAjaxStats(a){}function bindTogglePlusMinus(a,b,c){$(document).ready(function(){$("#"+b).bind("click",function(){$("#"+a).attr("src")==plus?$("#"+a).attr("src",minus):$("#"+a).attr("src",plus);$("#"+c).slideToggle("fast");return!1})})}function abrirEditar(a,b,c,d,e){get_ajax(a,b,c,d,e);document.getElementById("ajaxcontainer").style.height="auto"}
function get_ajax(a,b,c,d,e){a=base_url+"ajax/"+a+"?id="+e+"&p="+d+"&type="+b;$("#"+c).load(a)}function comment_reply(a){ref="#"+a+" ";textarea=$("#comment");if(0!=textarea.length){a=RegExp(ref);var b=textarea.val();b.match(a)||(0<b.length&&"\n"!=b.charAt(b.length-1)&&(b+="\n"),textarea.val(b+ref),textarea.get(0).focus())}}function appySmiley(a){textarea=$("#comment");a=textarea.val()+" {"+a+"}";textarea.val(a);textarea.focus();textarea.select()}
function cambiar_estado(a,b){if("formulario"==b)document.getElementById("link").OnClick="",document.getElementById("link").innerHTML='<input size="70" type="text" autocomplete="off" name="new_estado" id="new_estado" value="El texto ir\u00e1 aqu\u00ed" /><a onclick="javascript:cambiar_estado(0, \'guardar\')" title="guardar"><img class="icon tick img-flotante" src="/img/estructura/pixel.gif" alt="guardar" title="guardar">';else return alert(document.getElementById("link").OnClick),document.getElementById("link").innerHTML=
"actualizado",document.getElementById("link").OnClick="javascript:cambiar_estado("+a+", 'formulario')",!1};
