function update_votes_counter(a){var b=$("#votos-e-"+a).html(),d=$("#usuarios-totales-"+a).html();b++;d++;$("#votos-e-"+a).html(b);$("#usuarios-totales-"+a).html(d)}function update_comments_counter(a){var b=$("#opiniones-"+a).html();b++;$("#opiniones-"+a).html(b)}
function ajax_poll_vote(a){var b=new XMLHttpRequest,d=document.getElementById("cuenta_"+a).value,e=[],c=[];for(i=0;i<d;i++)e[i]=document.getElementById("opcion_"+a+"["+i+"]").checked;for(i=0;i<d;i++)c[i]=!0==e[i]?document.getElementById("opcion_"+a+"["+i+"]").value:0;b&&(b.onreadystatechange=function(){if(4==b.readyState){var c=b.responseText;document.getElementById("pollvotes"+a).innerHTML=String(c);update_votes_counter(a);return!0}},b.open("POST","/ajax/poll_vote.php",!0),b.setRequestHeader("Content-Type",
"application/x-www-form-urlencoded"),b.send("poll_id="+a+"&opciones="+c))}function setOpacity(a){obj=document.getElementById("ajaxcomments");container=document.getElementById("ajaxcontainer");obj.style.filter="alpha(opacity:"+a+")";obj.style.KHTMLOpacity=a/100;obj.style.MozOpacity=a/100;obj.style.opacity=a/100;container.style.height=a*obj.offsetHeight/100+10+"px"}function fadeIn(a){100>=a&&(setOpacity(a),window.setTimeout("fadeIn("+(a+50)+")",25))}
function startFade(){setOpacity(document.getElementById("ajaxcomments"),0);document.getElementById("ajaxcomments").style.visibility="visible";fadeIn(0)}
function submit_comment(){if(""==document.getElementById("poll_content").value)return document.getElementById("error_com").innerHTML="Comentario vac\u00edo",document.getElementById("spinner").className="ko",document.getElementById("poll_content").focus(),!1;var a=document.getElementById("poll_content").value,b=document.getElementById("process").value,d=document.getElementById("poll_id").value,e=document.getElementById("user_id").value,c=new XMLHttpRequest;c&&(document.getElementById("submit_com").disabled=
!0,document.getElementById("poll_content").disabled=!0,document.getElementById("spinner").className="loading",c.onreadystatechange=function(){if(4==c.readyState){var a=c.responseText;if("OK:"==String(a).substring(0,3))return document.getElementById("spinner").className="ok",document.getElementById("poll_content").value="",document.getElementById("ajaxcomments").innerHTML=String(a).substring(3),startFade(),update_comments_counter(id),!0;document.getElementById("spinner").className="ko";document.getElementById("submit_com").disabled=
!1;document.getElementById("plol_content").disabled=!1;document.getElementById("error_com").innerHTML=String(a).substring(3);return!1}},c.open("POST","/ajax/poll_com.php",!0),c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.send("poll_content="+encodeURIComponent(a)+"&process="+b+"&poll_id="+d+"&user_id="+e))}
function edit_comment(a){if(""==document.getElementById("comment_"+a).value)return document.getElementById("error_com_"+a).innerHTML="Comentario vac\u00edo",document.getElementById("spinner_"+a).className="spinner ko",document.getElementById("comment_"+a).focus(),!1;var b=document.getElementById("comment_"+a).value,d=document.getElementById("poll_id_"+a).value,e=document.getElementById("user_id_"+a).value,c=new XMLHttpRequest;c&&(document.getElementById("submit_com_"+a).disabled=!0,document.getElementById("comment_"+
a).disabled=!0,document.getElementById("spinner_"+a).className="spinner loading",c.onreadystatechange=function(){if(4==c.readyState){var b=c.responseText;if("OK:"==String(b).substring(0,3))return document.getElementById("spinner_"+a).className="spinner ok",document.getElementById("comment_"+a).value="",document.getElementById("ccontainer-"+a).innerHTML=String(b).substring(3),!0;document.getElementById("spinner_"+a).className="spinner ko";document.getElementById("submit_com_"+a).disabled=!1;document.getElementById("comment_"+
a).disabled=!1;document.getElementById("error_com_"+a).innerHTML=String(b).substring(3);return!1}},c.open("POST","/ajax/edit_poll_comment.php?id="+a,!0),c.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),c.send("id="+a+"&poll_content="+encodeURIComponent(b)+"&process=editcomment&poll_id="+d+"&user_id="+e))}
function edit_poll(a){var b=new XMLHttpRequest,d=document.getElementById("process-"+a).value;if("save_settings"==d){var e=document.getElementById("cuenta"+a).value,c=document.getElementById("titulo").value,f=document.getElementById("descripcion").value,g=[],h=[];for(i=0;i<e;i++)h[i]=document.getElementById("opcion"+i).value;for(i in h)g[i]=document.getElementById("valor"+i).value}b&&(b.onreadystatechange=function(){if(4==b.readyState){var e=b.responseText;document.getElementById("editbox-"+a).innerHTML=
String(e);"save_settings"==d&&save_options(a,g,d,c,f);return!0}},b.open("POST","/ajax/polls_utils.php",!0),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.send("poll_id="+a+"&process="+d))}
function save_options(a,b,d,e,c){var f=new XMLHttpRequest;f&&(f.onreadystatechange=function(){if(4==f.readyState){var b=f.responseText;document.getElementById("pollvotes"+a).innerHTML=String(b);return!0}},f.open("POST","/ajax/polls_utils.php",!0),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.send("poll_id="+a+"&process="+d+"&opciones="+b+"&titulo="+e+"&descripcion="+c))}
function delete_poll(a){var b=new XMLHttpRequest;b&&(b.onreadystatechange=function(){if(4==b.readyState)return document.getElementById("encuesta"+a).innerHTML="",!0},b.open("POST","/ajax/poll_delete.php",!0),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.send("poll_id="+a))}
function add_option(){var a=document.getElementsByTagName("dt").length,b=document.getElementById("encuesta-opciones"),d=document.createElement("dt"),e=document.createElement("dd");if(15==a)return alert("Has superado el n\u00famero de opciones m\u00e1ximas"),!0;previous=parseInt(a)-1;eliminar=document.getElementById("delete-"+previous);padre3=eliminar.parentNode;padre3.removeChild(eliminar);original=a;d.id="opcion-"+original;siguiente=parseInt(original)+1;d.innerHTML="opci\u00f3n "+siguiente;e.id=
"opcion-t-"+original;e.innerHTML='<input type="text" value="" size="70" name="opts['+original+']" id="opts['+original+']"> <span id="delete-'+original+'"> <a href="javascript:delete_option('+original+')"> <img class="icon delete" alt="eliminar opci\u00f3n" title="eliminar opci\u00f3n"></a></span>';b.appendChild(d);b.appendChild(e)}
function delete_option(a){previous=parseInt(a)-1;opcion=document.getElementById("opcion-"+a);cuadro=document.getElementById("opcion-t-"+a);contenido=document.getElementById("opts["+previous+"]").value;padre=opcion.parentNode;padre.removeChild(opcion);padre2=cuadro.parentNode;padre2.removeChild(cuadro);dd=document.getElementById("opcion-t-"+previous);dd.innerHTML='<input type="text" value="'+contenido+'" size="70" name="opts['+previous+']" id="opts['+previous+']"><span id="delete-'+previous+'"><a href="javascript:delete_option('+
previous+')" > <img class="icon delete" alt="eliminar opci\u00f3n" title="eliminar opci\u00f3n"></a></span>'};
