<script type="text/javascript">
<!--
var mnm_banner_font_pt = 8;
var mnm_banner_width = 425;
var mnm_banner_height = 55;
var mnm_banner_format = "horizontal";
var mnm_banner_color_border = "FFF"; 
var mnm_banner_color_bg = "FFF";
var mnm_banner_color_link = "FFF";
var mnm_banner_color_text = "EEE";
var base_url = '/';
//--></script>
<script type="text/javascript" src="/api/show_banner.js.php"></script>

