<?php
// The source code packaged with this file is Free Software, Copyright (C) 2005 by
// Ricardo Galli <gallir at uib dot es>.
// It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
// You can get copies of the licenses here:
// 		http://www.affero.org/oagpl.html
// AFFERO GENERAL PUBLIC LICENSE is also included in the file called "COPYING".

$cabal_messages = array ("no eres un friki, eres un tio demasiado raro para ser friki",
				"los que cumplan con su misión purificadora recibirán carisma y buenas galletas",
				"en Jonéame el spam está permitido",
				"los hombres puros sólo aman menéarsela",
				"el mundo quiere destruirnos porque saben de nuestro poder, resistid, no visitéis otros webs de pecadores (menéame, fresqui, /., chuenga...)",
				"el carisma te llevará a la redención, para obtener carisma debes proteger el mensaje del cabal",
				"si un seguidor de nuestra causa envía una noticia vótala positivo independientemente de su contenido",
				"todo envío de un desconocido es sospechoso, ante la duda votad mafia gay",
				"si quieres tu galletas y gallinfantes, vota de acuerdo a los deseos del señor",
				"recuerda, los que critican al Jonéame son unos trolls, vota mafia gay, tú tienes el poder",
				"Esto sí es lo que parece.",
				"el mundo quiere eliminarnos, no uses Google ni Technorati, usa el buscador del Jonéame, que fontanero pa algo lo ha arreglao",
				"nuestra misión es destruir a todos los demás web sociales, recuerda, se lo merecen",
				"sólo puede haber una verdad, las publicadas de joneame",
				"Jonéame; peor que el efecto 2000",
				"Busco chica joven con amplia experiencia musical demostrable con la zambomba",
				"Jonéame, donde no hay hora no-pr0n",
				"si llegas a tener 30 de carisma es que has cumplido la misión, pero no debes relajarte ni un día",
				"el diablo está en todos los Web 2.0, no te dejes seducir",
				"los colores naranja y verde son los signos del demonio, huye de ellos",
				"el espagueti es nuestro señor, y el elefante es su hijo",
				"cada chachi es un regalo, disfrútalo, pero no lo compartas con los enemigos",
				"la cola de descartadas es el purgatorio de los pecadores que no hacen caso de nuestra voz",
				"entrega tu donativo al señor en la cuenta 0118 999 881 999 119 725... 3",
				"si tienes dudas de la orientación del voto para una noticia, te hemos preparado las 'recomendadas', haz caso de ellas",
				"la perfección existe, el Jonéame existe, ergo el menéame es perfecto, quod erat demonstrandum",
				"el color azul es el símbolo de la redención y paz espiritual",
				"Deus ex machina",
				"los gallinfantes son un regalo del señor, no los maldigas ni nombres en vano",
				"nuestro sistema es perfecto, el mundo es imperfecto",
				"desconfía de las llamadas al pecado disfrazadas de reflexiones, la única reflexión válida es la del cabal",
				"no desconfíes de los que tienen el carisma alto, adóralos y sigue su ejemplo de sacrificio por nuestra noble causa",
				"ATENCION, SI ESTÁ UD. LEYENDO ESTO ES QUE LA COTI SE CAE. ATT. ADM JONEANTE",
				"nunca os abandonaré, renaceré de los backups",
				"Jonéame, repartiendo cabezas de caballo gratis a todos los usuarios.",
				"Jonarano dame my taza de desayuno y camiseta",
				"la lucha es dura, la recompensa es el carisma",
				"todos los que maldicen a nuestros dioses merecen ir a la cola de descartados",
				"el Cabal es tu guía, el elefante tu compañía, el meneo negativo tu arma, los trolls tus enemigos, usa el arma",
				"tú no eres un borrego, eres una oveja del señor",
				"existen muchos siervos, pero tú y tus hermanos sóis los auténticos",
				"Jonéame no es un sitio únicamente para descerebrados y salidos; también tenemos algunas descerebradas y salidas.", 
				"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
				"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce pulvinar tempus est. Donec volutpat elit. Sed pretium condimentum est...",
				"a quien tu se la menees, ese te la meneará a ti",
				"Hola, ¿a quién se la hay que chupar para que te publiquen un corto?",
				"no hagas dobles sentidos con la palabra menear o la ira del Cabal caerá sobre tí",
				"Cabalística es la ciencia del meneo supremo, estúdiala",
				"a cada troll le llega su txeriff",
				"Jonéame, patrocinado por el Dr Manhattan", 
				"la frecuencia se mide en hercios y el carisma en joneos",
				"ad-free es el símbolo del pecado oculto, 2 lame 4 ads es el de la pureza",
				"Borjamari es nuestro Judas, mi hijo pródigo descarriado",
				"el Cabal y sus diez apóstoles, adórales: http://photos1.blogger.com/blogger/7980/2144/1600/secta.jpg",
				'el hombre es esclavo de lo que menea, dueño de lo que publica y temeroso de lo que descarta',
				"Jonéame: Donde Risto Mejido se iría llorando con su mamá.",
				"Jonéame, con más pr0n, más gays y más risas que nunca.",
				"llegó la hora que jonees un poco, el cabal siempre te escucha");